name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: "Test (Node: ${{matrix.node-version}})"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        node-version:
        - 18
        - 20
        - 22
    env:
      NGROK_API_KEY: dummy-api-key # The tests crash if NGROK_API_KEY is not set
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run test
